[package]
name = "gti"
version = "0.1.0"
authors = ["Begley Brothers Ltd"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goose = { version = "^0.11", features = ["gaggle"] }

[[bin]]
name = "gti"
path = "gti.rs"