version: "3"
services:
  the-internet.int:
    image: the-internet
    container_name: the-internet.int
    hostname: the-internet
    domainname: int
    environment:
      - APP_NAME=bionic-frr-7
    ports:
      - "5000:5000"
    restart: on-failure
    networks:
      int:
        - the-internet
  gaggle.int:
    image: gti
    container_name: gaggle.int
    hostname: gaggle
    domainname: int
    depends_on:
      - the-internet
    entrypoint:
      - /usr/local/bin/gti --manager --expect-workers --host http://the-internet.int:5000 --log-file /gaggle.log --report-file /gaggle.html
      - sleep 3s
      - /usr/local/bin/gti --worker --manager-host gaggle.int --log-file /003-swanling.log --report-file /003-swanling.html
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
    restart: on-failure
    volumes:
      - ./log/gaggle.log:/gaggle.log
      - ./report/gaggle.html:/gaggle.html
      - ./log/003-swanling.log:/003-swanling.log
      - ./report/003-swanling.html:/003-swanling.html
    networks:
      int:
        - gaggle
  001-swanling.int:
    image: gti
    container_name: 001-swanling.int
    hostname: 001-swanling
    domainname: int
    depends_on:
      - gaggle
    entrypoint:
      - /usr/local/bin/gti --worker --manager-host gaggle.int --log-file /001-swanling.log --report-file /001-swanling.html
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
    restart: on-failure
    volumes:
      - ./log/001-swanling.log:/001-swanling.log
      - ./report/001-swanling.html:/001-swanling.html
    networks:
      int:
        - 001-swanling
  002-swanling.int:
    image: gti
    container_name: 002-swanling.int
    hostname: 002-swanling
    domainname: int
    depends_on:
      - 001-swanling
    entrypoint:
      - /usr/local/bin/gti --worker --manager-host gaggle.int --log-file /002-swanling.log --report-file /002-swanling.html
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
    restart: on-failure
    volumes:
      - ./log/002-swanling.log:/002-swanling.log
      - ./report/002-swanling.html:/002-swanling.html
    networks:
      int:
        - 002-swanling

networks:
  int:
    driver: bridge
