apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath --out podman-pod.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: the-internet
      name: the-internet
    spec:
      ports:
        - name: "5000"
          port: 5000
          targetPort: 5000
      selector:
        io.kompose.service: the-internet
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath --out podman-pod.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/systemctl-net: "true"
        io.kompose.service: 001-goose
      name: 001-goose
    spec:
      containers:
        - command:
            - /usr/local/bin/gti --worker --manager-host 172.33.0.5 --log-file /001-goose.log --report-file /001-goose.html
          env:
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
          image: gti
          name: 001-goose
          resources: {}
          volumeMounts:
            - mountPath: /001-goose.log
              name: 001-goose-hostpath0
            - mountPath: /001-goose.html
              name: 001-goose-hostpath1
      restartPolicy: OnFailure
      volumes:
        - hostPath:
            path: /home/hedge/src/goose/examples/the-internet/log/001-goose.log
          name: 001-goose-hostpath0
        - hostPath:
            path: /home/hedge/src/goose/examples/the-internet/report/001-goose.html
          name: 001-goose-hostpath1
    status: {}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      creationTimestamp: null
      name: systemctl-net
    spec:
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  io.kompose.network/systemctl-net: "true"
      podSelector:
        matchLabels:
          io.kompose.network/systemctl-net: "true"
  - apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath --out podman-pod.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/systemctl-net: "true"
        io.kompose.service: 002-goose
      name: 002-goose
    spec:
      containers:
        - command:
            - /usr/local/bin/gti --worker --manager-host 172.33.0.5 --log-file /002-goose.log --report-file /002-goose.html
          env:
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
          image: gti
          name: 002-goose
          resources: {}
          volumeMounts:
            - mountPath: /002-goose.log
              name: 002-goose-hostpath0
            - mountPath: /002-goose.html
              name: 002-goose-hostpath1
      restartPolicy: OnFailure
      volumes:
        - hostPath:
            path: /home/hedge/src/goose/examples/the-internet/log/002-goose.log
          name: 002-goose-hostpath0
        - hostPath:
            path: /home/hedge/src/goose/examples/the-internet/report/002-goose.html
          name: 002-goose-hostpath1
    status: {}
  - apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath --out podman-pod.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/systemctl-net: "true"
        io.kompose.service: gaggle
      name: gaggle
    spec:
      containers:
        - command:
            - /usr/local/bin/gti --manager --expect-workers --host http://172.33.0.2:5000 --log-file /gaggle.log --report-file /gaggle.html
            - sleep 3s
            - /usr/local/bin/gti --worker --manager-host 172.33.0.5 --log-file /003-goose.log --report-file /003-goose.html
          env:
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
          image: gti
          name: gaggle
          resources: {}
          volumeMounts:
            - mountPath: /gaggle.log
              name: gaggle-hostpath0
            - mountPath: /gaggle.html
              name: gaggle-hostpath1
            - mountPath: /003-goose.log
              name: gaggle-hostpath2
            - mountPath: /003-goose.html
              name: gaggle-hostpath3
      restartPolicy: OnFailure
      volumes:
        - hostPath:
            path: /home/hedge/src/goose/examples/the-internet/log/gaggle.log
          name: gaggle-hostpath0
        - hostPath:
            path: /home/hedge/src/goose/examples/the-internet/report/gaggle.html
          name: gaggle-hostpath1
        - hostPath:
            path: /home/hedge/src/goose/examples/the-internet/log/003-goose.log
          name: gaggle-hostpath2
        - hostPath:
            path: /home/hedge/src/goose/examples/the-internet/report/003-goose.html
          name: gaggle-hostpath3
    status: {}
  - apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath --out podman-pod.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/systemctl-net: "true"
        io.kompose.service: the-internet
      name: the-internet
    spec:
      containers:
        - env:
            - name: APP_NAME
              value: bionic-frr-7
          image: the-internet
          name: the-internet
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: OnFailure
    status: {}
kind: List
metadata: {}
