[book]
title = "The Swanling Book"
authors = ["Jeremy Andrews"]
description = "HTTP Load testing framework. Inspired by Locust and Taurus. Implemented with Rust."
language = "en"

[rust]
edition = "2018"

[build]
build-dir = "html"
create-missing = true

[output.html]
mathjax-support = true