name: Docs

on:
  push:
    branches:
    - 'main'
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-dev'
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-dev'
  pull_request:
    branches:
    - 'main'
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-dev'
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-dev'

env:
  RUST_BACKTRACE: 1

  deploy:
    name: Build and deploy book
    runs-on: ubuntu-latest
    needs: [style, build, linux]

    steps:
      - uses: actions/checkout@v2
      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.10"
      - name: Build and test Swanling book
        run: mdbook build book
      - name: Deploy Swanling book
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./book/html
          publish_branch: gh-pages
